/*
Project: Business metrics dashboard for a food delivery service (Saransk, May–June 2021)
Metric: LTV (Lifetime Value) of top-3 restaurants — total commission generated by each restaurant over the period
*/

WITH orders AS (
    SELECT
        analytics_events.rest_id,
        analytics_events.city_id,
        revenue * commission AS commission_revenue
    FROM analytics_events
    JOIN cities
        ON analytics_events.city_id = cities.city_id
    WHERE revenue IS NOT NULL
      AND log_date BETWEEN '2021-05-01' AND '2021-06-30'
      AND city_name = 'Саранск'
)
SELECT
    rest_id,
    chain AS сhain_name,
    type AS cuisine type,
    ROUND(SUM(o.commission_revenue)::numeric, 2) AS ltv
FROM orders AS o
LEFT JOIN partners AS p
    USING (rest_id, city_id)
GROUP BY rest_id, chain, type
ORDER BY ltv DESC
LIMIT 3;