/*
Project: Business metrics dashboard for a food delivery service (Saransk, May–June 2021)
Metric: Top dishes by LTV — total commission generated by each dish within the top-2 LTV restaurants over the period
*/

-- Calculate commission revenue per order
WITH orders AS
    (SELECT analytics_events.rest_id,
            analytics_events.city_id,
            analytics_events.object_id,
            revenue * commission AS commission_revenue
     FROM analytics_events
     JOIN cities ON analytics_events.city_id = cities.city_id
     WHERE revenue IS NOT NULL
         AND log_date BETWEEN '2021-05-01' AND '2021-06-30'
         AND city_name = 'Саранск'), 

-- Identify the top-2 restaurants by LTV
top_ltv_restaurants AS
    (SELECT orders.rest_id,
            chain,
            type,
            ROUND(SUM(commission_revenue)::numeric, 2) AS LTV
     FROM orders
     JOIN partners ON orders.rest_id = partners.rest_id AND orders.city_id = partners.city_id
     GROUP BY 1, 2, 3
     ORDER BY LTV DESC
     LIMIT 2)

SELECT r.chain AS restaurant_chain,
       d.name AS dish_name,
       MAX(spicy) AS spicy,
       MAX(fish) AS fish,
       MAX(meat) AS meat,
       ROUND(SUM(commission_revenue)::numeric, 2) AS LTV
FROM orders AS o 
LEFT JOIN dishes AS d USING (rest_id, object_id)
JOIN top_ltv_restaurants AS r USING (rest_id)
GROUP BY r.chain, d.name
ORDER BY LTV DESC
LIMIT 5;